### ISSUE TITLE
Use dynamic key mapping

### ISSUE THREAD

**Issue by mebibou** [GPawi/Interview_Task_Oxford#2]
One improvement to make [here](https://github.com/GPawi/Interview_Task_Oxford/blob/main/convertCSV/convertCSV.py#L23-L37) would be to not have the `cycle.`, `site.`, etc statically set in the code, as these are not actually the full list of potential keys. Currently in Hestia the different Node types can be found on https://www.hestia.earth/schema/ looking at the top-level entries in the menu. But this could evolve over time... so having a code that works on any kind of Node would be ideal

**Comment by GPawi** [comment]
I adjusted the code and added two extensible dictionaries - one with the filter criteria to get the information per node, one with the sequential statements to merge the nodes. Of course, the dictionaries can be in separate files (e.g., with the full list of potential keys) that can be loaded into the code, but I wanted to keep it all in one place for now. Since I only have the input.csv and output.csv as examples to work with, I can only guess how well it will work with the entire dataset.
